const API_BASE = window.BMS_API_BASE || "http://127.0.0.1:8090";
let cachedSettingsRows = [];
let cachedRuntimeConfig = null;
let cachedUartStatus = null;
const statsState = {
	moduleId: 1,
	sinceMinutes: 60,
	zoomedChartKey: null
};
const CHART_COLORS = ["#58a6ff", "#29d391", "#ffc75f", "#ff8b94", "#8ad6ff", "#9d7dff", "#f89b29", "#7ddf64"];
const STATUS_DESCRIPTIONS = {
	155: {
		label: "Simulator nominal",
		note: "Default status generated by simulator."
	},
	144: {
		label: "Device reported",
		note: "Status seen from physical ingest source; exact bit meaning depends on vendor table."
	}
};

function initTabs() {
	const tabs = Array.from(document.querySelectorAll(".tab"));
	tabs.forEach((tab) => {
		tab.addEventListener("click", () => {
			tabs.forEach((t) => t.classList.remove("active"));
			tab.classList.add("active");

			const tabName = tab.getAttribute("data-tab");
			Array.from(document.querySelectorAll(".tab-content")).forEach((section) => {
				section.classList.toggle("active", section.id === `tab-${tabName}`);
			});
		});
	});
}

async function refreshHealth() {
	const el = document.getElementById("healthStatus");
	try {
		const response = await fetch(`${API_BASE}/api/health`);
		const json = await response.json();
		const dbState = json.dbConnected ? "DB OK" : "DB OFF";
		const modules = (json.modulesSeen || []).join(", ") || "none";
		const allowed = Array.isArray(json.allowedModules) && json.allowedModules.length
			? json.allowedModules.join(",")
			: "all";
		el.textContent = `Service: ${json.status.toUpperCase()} | ${dbState} | Modules: ${modules} | Allowed: ${allowed}`;
	} catch (err) {
		el.textContent = "Service unreachable";
	}
}

function renderLive(modules) {
	const grid = document.getElementById("moduleGrid");
	if (!Array.isArray(modules) || modules.length === 0) {
		grid.innerHTML = "<div class='module-card'>No telemetry yet.</div>";
		return;
	}

	grid.innerHTML = modules.map((item) => {
		const cells = Array.isArray(item.cellsMv) ? item.cellsMv : [];
		const statusInfo = describeStatus(item.statusCode);
		return `
			<div class="module-card">
				<h3>Module ${item.moduleId}</h3>
				<div class="metric"><span>Voltage</span><strong>${Number(item.voltageV).toFixed(3)} V</strong></div>
				<div class="metric"><span>Current</span><strong>${Number(item.currentA).toFixed(3)} A</strong></div>
				<div class="metric"><span>SOC</span><strong>${Number(item.socPercent).toFixed(2)} %</strong></div>
				<div class="metric"><span>Status</span><strong title="${escapeHtml(statusInfo.note)}">${item.statusCode} (${escapeHtml(statusInfo.label)})</strong></div>
				<div class="metric"><span>Cells</span><strong>${cells.length ? cells.join(" /") : "-"}</strong></div>
			</div>
		`;
	}).join("");
}

function renderEvents(events) {
	const tbody = document.getElementById("eventsTableBody");
	if (!Array.isArray(events) || events.length === 0) {
		tbody.innerHTML = "<tr><td colspan='5'>No events.</td></tr>";
		return;
	}

	tbody.innerHTML = events.map((event) => `
		<tr>
			<td>${event.timestamp || "-"}</td>
			<td>${event.moduleId || "-"}</td>
			<td>${event.severity || "-"}</td>
			<td>${event.eventCode || "-"}</td>
			<td>${event.message || "-"}</td>
		</tr>
	`).join("");
}

function renderStats(stats, moduleId) {
	const container = document.getElementById("statsCards");
	const timeLabel = formatMinutesLabel(statsState.sinceMinutes);
	if (!Array.isArray(stats) || stats.length === 0) {
		container.innerHTML = `<div class='stats-card'>No statistics available yet for module ${moduleId} in ${timeLabel}.</div>`;
		return;
	}

	const item = stats[0];
	const lastStatus = describeStatus(item.lastStatusCode);
	container.innerHTML = `
		<div class="stats-card">
			<h3>Module ${item.moduleId}</h3>
			<div class="metric"><span>Avg SOC</span><strong class="value">${Number(item.avgSoc).toFixed(2)} %</strong></div>
			<div class="metric"><span>SOC Range</span><strong>${Number(item.minSoc).toFixed(2)} - ${Number(item.maxSoc).toFixed(2)} %</strong></div>
			<div class="metric"><span>Voltage Range</span><strong>${Number(item.minVoltage).toFixed(3)} - ${Number(item.maxVoltage).toFixed(3)} V</strong></div>
			<div class="metric"><span>Current Range</span><strong>${Number(item.minCurrent).toFixed(3)} - ${Number(item.maxCurrent).toFixed(3)} A</strong></div>
			<div class="metric"><span>Time Window</span><strong>${timeLabel}</strong></div>
			<div class="metric"><span>Points</span><strong>${item.sampleCount}</strong></div>
			<div class="metric"><span>Last Status</span><strong title="${escapeHtml(lastStatus.note)}">${item.lastStatusCode} (${escapeHtml(lastStatus.label)})</strong></div>
			<div class="metric"><span>Last Timestamp</span><strong>${item.lastTimestamp || "-"}</strong></div>
		</div>
	`;
}

function formatMinutesLabel(minutes) {
	const value = Number(minutes);
	if (!Number.isFinite(value) || value <= 0) {
		return "All time";
	}
	if (value < 60) {
		return `${value} min`;
	}
	if (value % 60 === 0) {
		return `${value / 60} h`;
	}
	return `${value} min`;
}

function describeStatus(code) {
	const numeric = Number(code);
	const safe = Number.isFinite(numeric) ? Math.trunc(numeric) : 0;
	const unsigned = safe & 0xff;
	const hex = `0x${unsigned.toString(16).toUpperCase().padStart(2, "0")}`;
	const bin = unsigned.toString(2).padStart(8, "0");
	const known = STATUS_DESCRIPTIONS[safe];
	if (known) {
		return {
			label: known.label,
			note: `${known.note} Raw=${safe}, ${hex}, b${bin}`
		};
	}

	return {
		label: "Unknown",
		note: `No status mapping available yet. Raw=${safe}, ${hex}, b${bin}`
	};
}

function escapeHtml(value) {
	return String(value || "")
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;")
		.replace(/'/g, "&#039;");
}

function formatChartNumber(value, digits) {
	if (!Number.isFinite(value)) {
		return "-";
	}
	return Number(value).toFixed(digits);
}

function linePoints(values, minValue, maxValue, width, height, pad) {
	if (!Array.isArray(values) || values.length === 0) {
		return "";
	}
	const spanX = Math.max(width - pad * 2, 1);
	const spanY = Math.max(height - pad * 2, 1);
	const valueRange = Math.max(maxValue - minValue, 0.000001);
	const divisor = Math.max(values.length - 1, 1);
	const points = [];

	values.forEach((value, index) => {
		if (!Number.isFinite(value)) {
			return;
		}
		const x = pad + (index / divisor) * spanX;
		const y = height - pad - ((value - minValue) / valueRange) * spanY;
		points.push(`${x.toFixed(1)},${y.toFixed(1)}`);
	});

	return points.join(" ");
}

function buildSingleLineChart(values, color) {
	if (!Array.isArray(values) || values.length === 0) {
		return "<div class='chart-empty'>No chart data.</div>";
	}

	const width = 420;
	const height = 180;
	const pad = 20;
	const minValue = Math.min(...values);
	const maxValue = Math.max(...values);
	const adjustedMin = minValue === maxValue ? minValue - 1 : minValue;
	const adjustedMax = minValue === maxValue ? maxValue + 1 : maxValue;
	const points = linePoints(values, adjustedMin, adjustedMax, width, height, pad);

	return `
		<svg viewBox="0 0 ${width} ${height}" width="100%" height="180" role="img" aria-label="line chart">
			<rect x="0" y="0" width="${width}" height="${height}" fill="#142030" rx="6" ry="6"></rect>
			<line x1="${pad}" y1="${pad}" x2="${pad}" y2="${height - pad}" stroke="#3a4c62" stroke-width="1"></line>
			<line x1="${pad}" y1="${height - pad}" x2="${width - pad}" y2="${height - pad}" stroke="#3a4c62" stroke-width="1"></line>
			<polyline points="${points}" fill="none" stroke="${color}" stroke-width="2.3" stroke-linejoin="round" stroke-linecap="round"></polyline>
		</svg>
	`;
}

function buildMultiLineChart(series) {
	const definedValues = [];
	series.forEach((entry) => {
		entry.values.forEach((value) => {
			if (Number.isFinite(value)) {
				definedValues.push(value);
			}
		});
	});

	if (!definedValues.length) {
		return "<div class='chart-empty'>No cell chart data.</div>";
	}

	const width = 420;
	const height = 180;
	const pad = 20;
	const minValue = Math.min(...definedValues);
	const maxValue = Math.max(...definedValues);
	const adjustedMin = minValue === maxValue ? minValue - 1 : minValue;
	const adjustedMax = minValue === maxValue ? maxValue + 1 : maxValue;

	const polylines = series.map((entry) => {
		const points = linePoints(entry.values, adjustedMin, adjustedMax, width, height, pad);
		if (!points) {
			return "";
		}
		return `<polyline points="${points}" fill="none" stroke="${entry.color}" stroke-width="1.8" stroke-linejoin="round" stroke-linecap="round"></polyline>`;
	}).join("");

	return `
		<svg viewBox="0 0 ${width} ${height}" width="100%" height="180" role="img" aria-label="multi line chart">
			<rect x="0" y="0" width="${width}" height="${height}" fill="#142030" rx="6" ry="6"></rect>
			<line x1="${pad}" y1="${pad}" x2="${pad}" y2="${height - pad}" stroke="#3a4c62" stroke-width="1"></line>
			<line x1="${pad}" y1="${height - pad}" x2="${width - pad}" y2="${height - pad}" stroke="#3a4c62" stroke-width="1"></line>
			${polylines}
		</svg>
	`;
}

function renderStatisticsCharts(history, moduleId) {
	const container = document.getElementById("statsCharts");
	if (!Array.isArray(history) || history.length === 0) {
		statsState.zoomedChartKey = null;
		container.innerHTML = `<div class="chart-card"><div class="chart-empty">No history data for module ${moduleId} yet.</div></div>`;
		return;
	}
	const zoomedKey = statsState.zoomedChartKey;

	const ordered = [...history].reverse();
	const voltage = ordered.map((item) => Number(item.voltageV/10));
	const current = ordered.map((item) => Number(item.currentA));
	const soc = ordered.map((item) => Number(item.socPercent));
	const status = ordered.map((item) => Number(item.statusCode));
	const latestStatusInfo = describeStatus(status[status.length - 1]);

	const maxCellCount = ordered.reduce((max, item) => {
		const cells = Array.isArray(item.cellsMv) ? item.cellsMv : [];
		return Math.max(max, cells.length);
	}, 0);

	const cellSeries = [];
	for (let i = 0; i < maxCellCount; i += 1) {
		const values = ordered.map((item) => {
			const cells = Array.isArray(item.cellsMv) ? item.cellsMv : [];
			const value = Number(cells[i]);
			return Number.isFinite(value) ? value : NaN;
		});
		if (values.some((value) => Number.isFinite(value))) {
			cellSeries.push({
				name: `Cell ${i + 1}`,
				color: CHART_COLORS[i % CHART_COLORS.length],
				values
			});
		}
	}

	const charts = [];
	charts.push(`
		<div class="chart-card ${zoomedKey === "voltage" ? "zoomed" : ""}" data-chart-key="voltage">
			<div class="chart-card-head"><h3>Voltage (V)</h3><button class="chart-zoom-toggle" type="button">${zoomedKey === "voltage" ? "Shrink" : "Enlarge"}</button></div>
			${buildSingleLineChart(voltage, "#58a6ff")}
			<div class="chart-meta"><span>Min: ${formatChartNumber(Math.min(...voltage), 3)}</span><span>Max: ${formatChartNumber(Math.max(...voltage), 3)}</span><span>Latest: ${formatChartNumber(voltage[voltage.length - 1], 3)}</span></div>
		</div>
	`);

	charts.push(`
		<div class="chart-card ${zoomedKey === "current" ? "zoomed" : ""}" data-chart-key="current">
			<div class="chart-card-head"><h3>Current (A)</h3><button class="chart-zoom-toggle" type="button">${zoomedKey === "current" ? "Shrink" : "Enlarge"}</button></div>
			${buildSingleLineChart(current, "#ffc75f")}
			<div class="chart-meta"><span>Min: ${formatChartNumber(Math.min(...current), 3)}</span><span>Max: ${formatChartNumber(Math.max(...current), 3)}</span><span>Latest: ${formatChartNumber(current[current.length - 1], 3)}</span></div>
		</div>
	`);

	charts.push(`
		<div class="chart-card ${zoomedKey === "soc" ? "zoomed" : ""}" data-chart-key="soc">
			<div class="chart-card-head"><h3>SOC (%)</h3><button class="chart-zoom-toggle" type="button">${zoomedKey === "soc" ? "Shrink" : "Enlarge"}</button></div>
			${buildSingleLineChart(soc, "#29d391")}
			<div class="chart-meta"><span>Min: ${formatChartNumber(Math.min(...soc), 2)}</span><span>Max: ${formatChartNumber(Math.max(...soc), 2)}</span><span>Latest: ${formatChartNumber(soc[soc.length - 1], 2)}</span></div>
		</div>
	`);

	charts.push(`
		<div class="chart-card ${zoomedKey === "status" ? "zoomed" : ""}" data-chart-key="status">
			<div class="chart-card-head"><h3>Status Code</h3><button class="chart-zoom-toggle" type="button">${zoomedKey === "status" ? "Shrink" : "Enlarge"}</button></div>
			${buildSingleLineChart(status, "#ff8b94")}
			<div class="chart-meta"><span>Min: ${formatChartNumber(Math.min(...status), 0)}</span><span>Max: ${formatChartNumber(Math.max(...status), 0)}</span><span>Latest: ${formatChartNumber(status[status.length - 1], 0)}</span></div>
			<div class="chart-meta"><span title="${escapeHtml(latestStatusInfo.note)}">Latest meaning: ${escapeHtml(latestStatusInfo.label)}</span></div>
		</div>
	`);

	if (cellSeries.length) {
		const legend = cellSeries.map((entry) => {
			const latest = entry.values[entry.values.length - 1];
			return `<span class="chart-legend-item"><span class="chart-legend-dot" style="background:${entry.color}"></span>${escapeHtml(entry.name)}: ${formatChartNumber(latest, 0)} mV</span>`;
		}).join("");

		charts.push(`
			<div class="chart-card ${zoomedKey === "cells" ? "zoomed" : ""}" data-chart-key="cells">
				<div class="chart-card-head"><h3>Cell Voltages (mV)</h3><button class="chart-zoom-toggle" type="button">${zoomedKey === "cells" ? "Shrink" : "Enlarge"}</button></div>
				${buildMultiLineChart(cellSeries)}
				<div class="chart-meta"><span>Cells: ${cellSeries.length}</span><span>Samples: ${ordered.length}</span></div>
				<div class="chart-legend">${legend}</div>
			</div>
		`);
	} else if (statsState.zoomedChartKey === "cells") {
		statsState.zoomedChartKey = null;
	}

	container.innerHTML = charts.join("");
}

function sanitizeTimeRange(value) {
	const parsed = Number(value);
	if (!Number.isFinite(parsed)) {
		return statsState.sinceMinutes;
	}
	return Math.min(1440, Math.max(5, Math.round(parsed)));
}

function wireStatisticsControls() {
	const moduleSelect = document.getElementById("statsModuleFilter");
	const rangeSelect = document.getElementById("statsTimeRange");
	const reloadButton = document.getElementById("statsReloadBtn");
	const chartsContainer = document.getElementById("statsCharts");

	if (!moduleSelect || !rangeSelect || !reloadButton || !chartsContainer) {
		return;
	}

	statsState.moduleId = Number(moduleSelect.value) || 1;
	statsState.sinceMinutes = sanitizeTimeRange(rangeSelect.value);
	rangeSelect.value = String(statsState.sinceMinutes);

	moduleSelect.addEventListener("change", async () => {
		statsState.moduleId = Number(moduleSelect.value) || 1;
		await refreshStatistics();
	});

	rangeSelect.addEventListener("change", async () => {
		statsState.sinceMinutes = sanitizeTimeRange(rangeSelect.value);
		rangeSelect.value = String(statsState.sinceMinutes);
		await refreshStatistics();
	});

	reloadButton.addEventListener("click", async () => {
		statsState.sinceMinutes = sanitizeTimeRange(rangeSelect.value);
		rangeSelect.value = String(statsState.sinceMinutes);
		await refreshStatistics();
	});

	chartsContainer.addEventListener("click", (event) => {
		const button = event.target.closest(".chart-zoom-toggle");
		if (!button) {
			return;
		}
		const card = button.closest(".chart-card");
		if (!card) {
			return;
		}
		const chartKey = card.getAttribute("data-chart-key") || null;

		const willZoom = !card.classList.contains("zoomed");
		Array.from(chartsContainer.querySelectorAll(".chart-card.zoomed")).forEach((item) => {
			item.classList.remove("zoomed");
			const itemButton = item.querySelector(".chart-zoom-toggle");
			if (itemButton) {
				itemButton.textContent = "Enlarge";
			}
		});

		if (willZoom) {
			card.classList.add("zoomed");
			button.textContent = "Shrink";
			statsState.zoomedChartKey = chartKey;
		} else {
			card.classList.remove("zoomed");
			button.textContent = "Enlarge";
			statsState.zoomedChartKey = null;
		}
	});
}

async function refreshStatistics() {
	const moduleId = statsState.moduleId;
	const sinceMinutes = statsState.sinceMinutes;

	try {
		const [statsResponse, historyResponse] = await Promise.all([
			fetch(`${API_BASE}/api/statistics?moduleId=${moduleId}&sinceMinutes=${sinceMinutes}`),
			fetch(`${API_BASE}/api/history?moduleId=${moduleId}&sinceMinutes=${sinceMinutes}&limit=2000`)
		]);
		const [stats, history] = await Promise.all([
			statsResponse.json(),
			historyResponse.json()
		]);
		renderStats(stats, moduleId);
		renderStatisticsCharts(history, moduleId);
	} catch (err) {
		renderStats([], moduleId);
		renderStatisticsCharts([], moduleId);
	}
}

function statusBadge(online) {
	return `<span class="status-badge ${online ? "ok" : "off"}">${online ? "ONLINE" : "OFFLINE"}</span>`;
}

function renderRpiStatus(status) {
	const summary = document.getElementById("rpiStatusSummary");
	const sourcesBody = document.getElementById("rpiSourcesTableBody");
	const modulesBody = document.getElementById("rpiModulesTableBody");

	if (!status || typeof status !== "object") {
		summary.textContent = "No status data available.";
		sourcesBody.innerHTML = "<tr><td colspan='6'>No sources.</td></tr>";
		modulesBody.innerHTML = "<tr><td colspan='4'>No module status.</td></tr>";
		return;
	}

	const sources = Array.isArray(status.sources) ? status.sources : [];
	const modules = Array.isArray(status.modules) ? status.modules : [];
	const threshold = Number(status.offlineThresholdSec || 0);

	summary.innerHTML = `Overall: ${statusBadge(!!status.overallOnline)} | Offline threshold: <strong>${threshold}s</strong>`;

	if (!sources.length) {
		sourcesBody.innerHTML = "<tr><td colspan='6'>No ingest sources recorded yet.</td></tr>";
	} else {
		sourcesBody.innerHTML = sources.map((source) => `
			<tr>
				<td>${source.source || "-"}</td>
				<td>${source.lastSeen || "-"}</td>
				<td>${Number(source.secondsSinceSeen) >= 0 ? Number(source.secondsSinceSeen) : "-"}</td>
				<td>${statusBadge(!!source.online)}</td>
				<td>${source.acceptedCount ?? "-"}</td>
				<td>${source.lastModuleId ?? "-"}</td>
			</tr>
		`).join("");
	}

	if (!modules.length) {
		modulesBody.innerHTML = "<tr><td colspan='4'>No modules reported yet.</td></tr>";
	} else {
		modulesBody.innerHTML = modules.map((module) => `
			<tr>
				<td>${module.moduleId}</td>
				<td>${module.lastSeen || "-"}</td>
				<td>${Number(module.secondsSinceSeen) >= 0 ? Number(module.secondsSinceSeen) : "-"}</td>
				<td>${statusBadge(!!module.online)}</td>
			</tr>
		`).join("");
	}
}

function renderSettings(modules) {
	const tableBody = document.getElementById("settingsTableBody");
	const keySelect = document.getElementById("settingsKey");

	if (!Array.isArray(modules) || modules.length === 0) {
		tableBody.innerHTML = "<tr><td colspan='6'>No settings available.</td></tr>";
		keySelect.innerHTML = "";
		cachedSettingsRows = [];
		return;
	}

	const modulesById = new Map();
	modules.forEach((module) => {
		modulesById.set(Number(module.moduleId), module.settings || []);
	});

	const rowByKey = new Map();
	modules.forEach((module) => {
		(module.settings || []).forEach((setting) => {
			if (!rowByKey.has(setting.key)) {
				rowByKey.set(setting.key, {
					key: setting.key,
					label: setting.label,
					unit: setting.unit,
					min: setting.min,
					max: setting.max,
					writable: !!setting.writable,
					values: {}
				});
			}
			rowByKey.get(setting.key).values[module.moduleId] = setting.value;
		});
	});

	cachedSettingsRows = Array.from(rowByKey.values());

	tableBody.innerHTML = cachedSettingsRows.map((row) => {
		const rw = row.writable ? "" : " (RO)";
		return `
			<tr>
				<td>${row.label}${rw}</td>
				<td>${row.unit}</td>
				<td>${formatSettingValue(row.values[1])}</td>
				<td>${formatSettingValue(row.values[2])}</td>
				<td>${formatSettingValue(row.values[3])}</td>
				<td>${formatSettingValue(row.values[4])}</td>
			</tr>
		`;
	}).join("");

	keySelect.innerHTML = cachedSettingsRows
		.filter((row) => row.writable)
		.map((row) => `<option value="${row.key}">${row.label} (${row.unit})</option>`)
		.join("");
}

function formatSettingValue(value) {
	if (typeof value === "undefined") {
		return "-";
	}
	return Number(value).toFixed(3);
}

function wireSettingsForm() {
	const form = document.getElementById("settingsForm");
	if (!form) {
		return;
	}

	form.addEventListener("submit", async (event) => {
		event.preventDefault();
		const moduleId = document.getElementById("settingsModule").value;
		const key = document.getElementById("settingsKey").value;
		const value = document.getElementById("settingsValue").value;
		const statusEl = document.getElementById("settingsStatus");

		if (!key) {
			statusEl.textContent = "No writable setting available.";
			return;
		}

		try {
			const body = new URLSearchParams({ moduleId, key, value }).toString();
			const response = await fetch(`${API_BASE}/api/cell-settings`, {
				method: "POST",
				headers: { "Content-Type": "application/x-www-form-urlencoded" },
				body
			});
			if (!response.ok) {
				const errJson = await response.json();
				statusEl.textContent = `Update failed: ${errJson.error || response.status}`;
				statusEl.style.color = "#ff6b6b";
				return;
			}
			statusEl.textContent = "Setting updated.";
			statusEl.style.color = "#29d391";
			await refreshSettings();
		} catch (error) {
			statusEl.textContent = "Update failed: service unreachable";
			statusEl.style.color = "#ff6b6b";
		}
	});
}

function renderRuntimeConfig(config) {
	const portInput = document.getElementById("serialPortValue");
	const meta = document.getElementById("serialConfigMeta");
	if (!portInput || !meta) {
		return;
	}

	if (!config || typeof config !== "object") {
		portInput.value = "";
		meta.textContent = "Runtime config unavailable.";
		return;
	}

	cachedRuntimeConfig = config;
	const ports = Array.isArray(config.availablePorts) ? [...config.availablePorts] : ["SIMULATED"];
	const selected = String(config.serialPort || "").trim().toUpperCase();
	if (selected && !ports.includes(selected)) {
		ports.push(selected);
	}
	portInput.innerHTML = ports
		.map((port) => `<option value="${escapeHtml(port)}">${escapeHtml(port)}</option>`)
		.join("");
	portInput.value = selected || "SIMULATED";
	const bmsState = config.bmsConnected ? "telemetry detected" : "no BMS telemetry yet";
	meta.textContent = `Saved in: ${config.envPath || ".env"} | ${bmsState}. Available options: ${ports.join(", ")}.`;
}

function renderUartStatus(status) {
	const meta = document.getElementById("uartRuntimeMeta");
	const logs = document.getElementById("uartLogs");
	if (!meta || !logs) {
		return;
	}

	if (!status || typeof status !== "object") {
		meta.textContent = "UART status unavailable.";
		logs.textContent = "No UART logs yet.";
		return;
	}

	cachedUartStatus = status;
	meta.textContent = status.running
		? `UART sender is running on ${status.serialPort || "-"}.`
		: "UART sender is stopped.";
	logs.textContent = Array.isArray(status.logs) && status.logs.length
		? status.logs.join("\n")
		: "No UART logs yet.";
}

function wireRuntimeConfigForm() {
	const form = document.getElementById("serialConfigForm");
	if (!form) {
		return;
	}

	form.addEventListener("submit", async (event) => {
		event.preventDefault();
		const portInput = document.getElementById("serialPortValue");
		const statusEl = document.getElementById("serialConfigStatus");
		const serialPort = String(portInput?.value || "").trim().toUpperCase();

		if (!/^(COM\d+|SIMULATED)$/.test(serialPort)) {
			statusEl.textContent = "Enter COM3, COM5 or SIMULATED.";
			statusEl.style.color = "#ff6b6b";
			return;
		}

		try {
			const body = new URLSearchParams({ serialPort }).toString();
			const response = await fetch(`${API_BASE}/api/runtime-config`, {
				method: "POST",
				headers: { "Content-Type": "application/x-www-form-urlencoded" },
				body
			});
			const json = await response.json();
			if (!response.ok) {
				statusEl.textContent = `Save failed: ${json.error || response.status}`;
				statusEl.style.color = "#ff6b6b";
				return;
			}
			statusEl.textContent = json.message || "COM port saved.";
			statusEl.style.color = "#29d391";
			await refreshRuntimeConfig();
		} catch (error) {
			statusEl.textContent = "Save failed: service unreachable";
			statusEl.style.color = "#ff6b6b";
		}
	});
}

async function refreshRuntimeConfig() {
	try {
		const response = await fetch(`${API_BASE}/api/runtime-config`);
		const config = await response.json();
		renderRuntimeConfig(config);
	} catch (error) {
		renderRuntimeConfig(null);
	}
}

function wireUartControls() {
	const startBtn = document.getElementById("uartStartBtn");
	const stopBtn = document.getElementById("uartStopBtn");
	const statusEl = document.getElementById("uartControlStatus");
	if (!startBtn || !stopBtn || !statusEl) {
		return;
	}

	startBtn.addEventListener("click", async () => {
		const port = String(document.getElementById("serialPortValue")?.value || "").trim().toUpperCase();
		if (!/^(COM\d+|SIMULATED)$/.test(port)) {
			statusEl.textContent = "Enter COM3, COM5 or SIMULATED first.";
			statusEl.style.color = "#ff6b6b";
			return;
		}

		try {
			const body = new URLSearchParams({ action: "start", serialPort: port }).toString();
			const response = await fetch(`${API_BASE}/api/uart-control`, {
				method: "POST",
				headers: { "Content-Type": "application/x-www-form-urlencoded" },
				body
			});
			const json = await response.json();
			if (!response.ok) {
				statusEl.textContent = `Start failed: ${json.error || response.status}`;
				statusEl.style.color = "#ff6b6b";
				return;
			}
			statusEl.textContent = `UART sender started on ${json.serialPort || port}.`;
			statusEl.style.color = "#29d391";
			renderUartStatus(json);
		} catch (error) {
			statusEl.textContent = "Start failed: service unreachable";
			statusEl.style.color = "#ff6b6b";
		}
	});

	stopBtn.addEventListener("click", async () => {
		try {
			const body = new URLSearchParams({ action: "stop" }).toString();
			const response = await fetch(`${API_BASE}/api/uart-control`, {
				method: "POST",
				headers: { "Content-Type": "application/x-www-form-urlencoded" },
				body
			});
			const json = await response.json();
			if (!response.ok) {
				statusEl.textContent = `Stop failed: ${json.error || response.status}`;
				statusEl.style.color = "#ff6b6b";
				return;
			}
			statusEl.textContent = "UART sender stopped.";
			statusEl.style.color = "#29d391";
			renderUartStatus(json);
		} catch (error) {
			statusEl.textContent = "Stop failed: service unreachable";
			statusEl.style.color = "#ff6b6b";
		}
	});
}

function wireBmsControls() {
	const resetBtn = document.getElementById("bmsResetBtn");
	const clearEventsBtn = document.getElementById("bmsClearEventsBtn");
	const clearStatisticsBtn = document.getElementById("bmsClearStatisticsBtn");
	const statusEl = document.getElementById("bmsControlStatus");
	if (!resetBtn || !clearEventsBtn || !clearStatisticsBtn || !statusEl) {
		return;
	}

	async function sendControl(action, confirmText) {
		const port = String(document.getElementById("serialPortValue")?.value || "").trim().toUpperCase();
		if (!/^(COM\d+|SIMULATED)$/.test(port)) {
			statusEl.textContent = "Choose a valid COM port or SIMULATED first.";
			statusEl.style.color = "#ff6b6b";
			return;
		}
		if (!window.confirm(confirmText)) {
			return;
		}

		try {
			const body = new URLSearchParams({ action, serialPort: port }).toString();
			const response = await fetch(`${API_BASE}/api/bms-control`, {
				method: "POST",
				headers: { "Content-Type": "application/x-www-form-urlencoded" },
				body
			});
			const json = await response.json();
			if (!response.ok) {
				statusEl.textContent = `Command failed: ${json.error || response.status}`;
				statusEl.style.color = "#ff6b6b";
				return;
			}
			statusEl.textContent = json.message || "Command sent.";
			statusEl.style.color = "#29d391";
		} catch (error) {
			statusEl.textContent = "Command failed: service unreachable";
			statusEl.style.color = "#ff6b6b";
		}
	}

	resetBtn.addEventListener("click", async () => {
		await sendControl("reset", "Send RESET BMS command?");
	});

	clearEventsBtn.addEventListener("click", async () => {
		await sendControl("clear-events", "Send CLEAR EVENTS command?");
	});

	clearStatisticsBtn.addEventListener("click", async () => {
		await sendControl("clear-statistics", "Send CLEAR STATISTICS command?");
	});
}

async function refreshUartStatus() {
	try {
		const response = await fetch(`${API_BASE}/api/uart-control`);
		const status = await response.json();
		renderUartStatus(status);
	} catch (error) {
		renderUartStatus(null);
	}
}

async function refreshSettings() {
	try {
		const response = await fetch(`${API_BASE}/api/cell-settings`);
		const settings = await response.json();
		renderSettings(settings);
	} catch (error) {
		renderSettings([]);
	}
}

async function refreshData() {
	try {
		const latestResponse = await fetch(`${API_BASE}/api/latest`);
		const latest = await latestResponse.json();
		renderLive(latest);
	} catch (err) {
		renderLive([]);
	}

	try {
		const eventsResponse = await fetch(`${API_BASE}/api/events?limit=40`);
		const events = await eventsResponse.json();
		renderEvents(events);
	} catch (err) {
		renderEvents([]);
	}

	try {
		await refreshStatistics();
	} catch (err) {
		renderStats([], statsState.moduleId);
		renderStatisticsCharts([], statsState.moduleId);
	}

	try {
		const rpiResponse = await fetch(`${API_BASE}/api/rpi-status`);
		const rpiStatus = await rpiResponse.json();
		renderRpiStatus(rpiStatus);
	} catch (err) {
		renderRpiStatus(null);
	}

	await refreshUartStatus();
	await refreshRuntimeConfig();
	await refreshSettings();
}

initTabs();
wireSettingsForm();
wireRuntimeConfigForm();
wireUartControls();
wireBmsControls();
wireStatisticsControls();
refreshHealth();
refreshData();
setInterval(refreshHealth, 3000);
setInterval(refreshData, 1000);
